# ./Taskfile.yaml
# See: https://taskfile.dev/api/

version: "3"

tasks:
  default: # Задача по умолчанию теперь ссылается на 'run-sso'
    cmds:
      - task: run-sso

  run-sso: # Новая задача для запуска программы
    desc: "Run SSO service"
    cmds:
      - go run cmd/sso/main.go --config=./config/local.yaml

  migrate:  ## Команда для миграции
    aliases: ## Алиасы команды, для простоты использования
      - mig
    desc: "Migrate sqlite"
    cmds:  ## Тут описываем необходимые bash-команды
      - go run ./cmd/migrator --storage-path=./storage/sso.db --migrations-path=./migrations

#go run ./cmd/migrator/main.go --storage-path=./storage/sso.db --migrations-path=./tests/migrations --migrations-table=migrations_test