# ./Taskfile.yaml
# See: https://taskfile.dev/api/

version: "3"

tasks:
  default: # Если не указать конкретную команду, будут выполнены дефолтные
    cmds:
      - task: migrate
  migrate:  ## Команда для генерации
    aliases: ## Алиасы команды, для простоты использования
      - mig
    desc: "Migrate sqlite"
    cmds:  ## Тут описываем необходимые bash-команды
      - go run ./cmd/migrator --storage-path=./storage/sso.db --migrations-path=./migrations